#!/usr/bin/env bash

# The Docker image tag is generated by Nix based on its inputs.
#
# This script provides a simple way of getting the current tag.

set -e
set -u
set -o pipefail

cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.."

SELF_IMAGE_NAME="$(nix --no-warn-dirty eval --raw '.#docker.imageName')"
SELF_IMAGE_TAG="$(nix --no-warn-dirty eval --raw '.#docker.imageTag')"
echo "${SELF_IMAGE_NAME}:${SELF_IMAGE_TAG}"
