[workspace.package]
version = "0.1.0"

[workspace]
members = [
  "crates/e2e-tests",
  "crates/ndc-citus",
  "crates/ndc-cockroach",
  "crates/ndc-postgres",
  "crates/other-db-tests",
  "crates/query-engine",
  "crates/tests-common"
]
