[workspace.package]
name = "postgres-ndc"
version = "0.1.0"

[workspace]
members = [
  "crates/query-engine",
  "crates/postgres-multitenant-ndc",
  "crates/gdc-client"
]

[profile.release]
debug = true

[profile.bench]
debug = true
