agents:
  queue: "aws-v3-build-node-common"
steps:
  - block: ":three_button_mouse: Click here to start the release"
    key: "artifact-release-gate"
    prompt: "Are you sure?"

  - label: ":docker: Build and push docker image"
    depends_on:
      - step: "artifact-release-gate"
    command: |
      set -eu -o pipefail

      TAG=$(git log -1 '--format=format:%h' --abbrev=9)
      DOCKER_TAG=$$DOCKER_REGISTRY/$$DOCKER_REPO:$$TAG

      echo "~~~ :docker: Configuring docker gcr helper"
      docker-credential-gcr configure-docker --registries=$$DOCKER_REGISTRY

      echo "~~~ :docker: Building ndc-postgres-config-server image"
      docker build --ssh default -t $$DOCKER_TAG -f ConfigServer.Dockerfile .

      echo "~~~ :docker: Pushing ndc-postgres-config-server image"
      docker push $$DOCKER_TAG

      echo "~~~ :docker: Removing ndc-postgres-config-server image"
      docker rmi $$DOCKER_TAG
    env:
      DOCKER_REGISTRY: us-docker.pkg.dev
      DOCKER_REPO: hasura-ddn/ddn/ndc-postgres-config-server
    plugins:
      - hasura/smooth-secrets#v1.3.2:
          secrets:
            - strategy: aws-secrets-manager
              key: github-user-keys/hasura-ci
              type: ssh
              region: us-east-2
      - gcp-workload-identity-federation#v1.0.0:
          # We can change the aud
          audience: "//iam.googleapis.com/projects/1025009031284/locations/global/workloadIdentityPools/hasura-ddn/providers/buildkite"
          service-account: "hasura-ci-docker-writer@hasura-ddn.iam.gserviceaccount.com"
      - hasura/smooth-checkout#v4.3.2:
          repos:
            - config:
                - url: git@github.com:hasura/postgres-ndc.git
          delete_checkout: true
          interpolate_checkout_path: "$BUILDKITE_BUILD_CHECKOUT_PATH/$BUILDKITE_BUILD_ID/$BUILDKITE_JOB_ID"