{
 "title": "Postgres NDC",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Total connection acquisition wait time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(postgres_ndc_connection_acquisition_wait_time_sum[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total query execution time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(postgres_ndc_query_execution_time_sum[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connection acquisition wait time (buckets)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(postgres_ndc_connection_acquisition_wait_time_bucket[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query execution time (buckets)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "rate(postgres_ndc_query_execution_time_bucket[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "rate(postgres_ndc_query_total[1m])"
    },
    { "expr": "postgres_ndc_explain_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Connection pool size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    { "expr": "postgres_ndc_pool_size", "legendFormat": "__auto" },
    {
     "expr": "postgres_ndc_pool_max_connections",
     "legendFormat": "__auto"
    },
    {
     "expr": "postgres_ndc_pool_min_connections",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}