#!/bin/bash
set -eu -o pipefail

# clean up our temporary docker config
if [[ -n "${BUILDKITE_DOCKER_CONFIG_TEMP_DIRECTORY:-}" && -d "$BUILDKITE_DOCKER_CONFIG_TEMP_DIRECTORY" ]]; then
  rm -rf "$BUILDKITE_DOCKER_CONFIG_TEMP_DIRECTORY"
fi