name: update-rust-toolchain
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: "0 9 * * mon" # runs at 9 am on every monday

jobs:
  update-rust-toolchain:
    name: "Update rust-toolchain"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: update rust toolchain
        uses: a-kenji/update-rust-toolchain@v1
        with:
          toolchain-path: ./rust-toolchain.toml
