on: [push]

name: CI

jobs:
  build_and_test:
    name: Test Postgres NDC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
      - uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./docker-compose.yaml"
          down-flags: "--volumes"
          services: |
            postgres
      - uses: actions-rs/cargo@v1
        env:
          POSTGRESQL_CONNECTION_STRING: postgresql://postgres:password@localhost:64002
          RUST_LOG: INFO
        with:
          command: test
