on: [push]

name: Postgres NDC tests

jobs:
  build_and_test:
    name: Test Postgres NDC
    runs-on: ubuntu-latest
    steps:
      # We need this because ndc-hub and ndc-multitenant are private repositores
      # and we are using deploy keys to access them.
      - name: Add SSH keys
        run: |
          mkdir -p /home/runner/.ssh
          echo "${{ secrets.HASURA_CI_USER_BASE64_ENCODED_SSH_KEY }}" | base64 --decode > /home/runner/.ssh/hasura-ci
          chmod 600 /home/runner/.ssh/hasura-ci
          cat > /home/runner/.ssh/config <<EOF
          IdentityFile /home/runner/.ssh/hasura-ci
          EOF

      - name: Install Protoc
        uses: arduino/setup-protoc@v2
        with:
          version: "23.3"

      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: Swatinem/rust-cache@v2

      - uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./docker-compose.yaml"
          down-flags: "--volumes"
          services: |
            postgres

      - uses: actions-rs/cargo@v1
        env:
          POSTGRESQL_CONNECTION_STRING: postgresql://postgres:password@localhost:64002
          RUST_LOG: INFO
          CARGO_NET_GIT_FETCH_WITH_CLI: "true"
        with:
          command: test

      # scream into Slack if something goes wrong
      - name: Report Status
        if: github.ref == 'refs/heads/master'
        uses: ravsamhq/notify-slack-action@v1
        with:
          status: ${{ job.status }}
          notify_when: failure
          notification_title: '😧 Error on <{repo_url}|{repo}>'
          message_format: '🐴 *{workflow}* {status_message} for <{repo_url}|{repo}>'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.BROKEN_BUILD_SLACK_WEBHOOK_URL }}
