on: [push]

name: Postgres NDC build

jobs:
  build_and_test:
    name: Build Postgres NDC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Protoc
        uses: arduino/setup-protoc@v2
        with:
          version: "23.3"

      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
        env:
          CARGO_NET_GIT_FETCH_WITH_CLI: "true"
          # fail on warnings
          RUSTFLAGS: "-D warnings"

      - name: lint
        uses: actions-rs/cargo@v1
        with:
          command: clippy
        env:
          CARGO_NET_GIT_FETCH_WITH_CLI: "true"
          # fail on warnings
          RUSTFLAGS: "-D warnings"

      # scream into Slack if something goes wrong
      - name: Report Status
        if: github.ref == 'refs/heads/main'
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
          notify_when: failure
          notification_title: '😧 Error on <{repo_url}|{repo}>'
          message_format: '🐴 *{workflow}* {status_message} for <{repo_url}|{repo}>'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.BROKEN_BUILD_SLACK_WEBHOOK_URL }}
