on: [push]

name: CI

jobs:
  build_and_test:
    name: Build Postgres NDC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install Protoc
        uses: arduino/setup-protoc@v2
        with:
          version: "23.3"
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
