on: [push]

name: Postgres NDC tests

jobs:
  build_and_test:
    name: Test Postgres NDC
    runs-on: ubuntu-latest
    steps:
      - name: Install Protoc
        uses: arduino/setup-protoc@v2
        with:
          version: "23.3"

      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: Swatinem/rust-cache@v2

      - uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./docker-compose.yaml"
          down-flags: "--volumes"
          services: |
            postgres

      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --exclude e2e-tests --workspace
        env:
          POSTGRESQL_CONNECTION_STRING: postgresql://postgres:password@localhost:64002
          RUST_LOG: INFO
          CARGO_NET_GIT_FETCH_WITH_CLI: "true"

      # scream into Slack if something goes wrong
      - name: Report Status
        if: github.ref == 'refs/heads/main'
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
          notify_when: failure
          notification_title: '😧 Error on <{repo_url}|{repo}>'
          message_format: '🐴 *{workflow}* {status_message} for <{repo_url}|{repo}>'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.BROKEN_BUILD_SLACK_WEBHOOK_URL }}
