name: "CI"

on:
  push:

jobs:
  formatting:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      # We need this because ndc-hub and ndc-multitenant are private repositores
      # and we are using deploy keys to access them.
      - name: Add SSH keys
        run: |
          mkdir -p /home/runner/.ssh
          echo "${{ secrets.HASURA_CI_USER_BASE64_ENCODED_SSH_KEY }}" | base64 --decode > /home/runner/.ssh/hasura-ci
          chmod 600 /home/runner/.ssh/hasura-ci
          cat > /home/runner/.ssh/config <<EOF
          IdentityFile /home/runner/.ssh/hasura-ci
          EOF

      - uses: actions/checkout@v3

      # Ensure rustfmt is installed and setup problem matcher
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt

      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1
        env:
          CARGO_NET_GIT_FETCH_WITH_CLI: "true"
